name: adivinanza
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  image_picker_loading_jm: ^0.0.4
  get_it: ^7.6.4
  flutter_native_splash: ^2.3.7
  flutter_ringtone_player: ^4.0.0+2
  google_cloud_translation: ^0.0.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/ringtone/

  fonts:
     - family: LilitaOne
       fonts:
         - asset: assets/fonts/LilitaOne-Regular.ttf

